### ISSUE TITLE
Помоги мне, я хочу использовать свой родной язык.

### ISSUE THREAD

**Issue by landomx** [4x11/build69#12]
У меня проблемы с использованием языка в игре. Я хочу использовать тайский вместо русского. Что мне делать? Большое спасибо.

**Comment by soly-olf** [comment]
замени русский на тайский

**Comment by landomx** [comment]
Где я должен решить?

**Comment by landomx** [comment]
> заменирусскийнатайский


Где я должен решить? Даже файлы, которые я никогда не знал, и я не разработчик Но моей стране нужно много Таиланда
