### ISSUE TITLE
How to fix the keyboard crash?

### ISSUE THREAD

**Issue by fet1sov** [4x11/build69#14]
When you start the Multiplayer the error happens in this line (keyboard.cpp):
`row->push_back(key);`

Can you please tell me how to fix it :(

**Comment by qqwrv-f10eq** [comment]
Just remove it @soly-olf  tell us.

**Comment by fet1sov** [comment]
How can this be done?
> Just remove it @soly-olf  tell us.

**Comment by soly-olf** [comment]
`//` or `/**/`

**Comment by fet1sov** [comment]
Thanks :3
