### ISSUE TITLE
Keyboard gone

### ISSUE THREAD

**Issue by parames3010** [4x11/build69#18]
How to fix keyboard gone?

it happen when i try comment on this line 
“row->push_back(key);”

Like this
//row->push_back(key);  on all in (keyboard.cpp)

Screen shot
![2ABFE843-ADAE-4DDA-9ADF-9E128F41755A](https://user-images.githubusercontent.com/8073243/57272501-2d712e00-70be-11e9-85dd-f5c2c7694805.jpeg)

**Comment by soly-olf** [comment]
uncomment

**Comment by parames3010** [comment]
I comment because game crash 
at line “row->push_back” << i check with Log(“”)
