### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by SteelSa** [4x11/build69#2]
Hello, do tell me please why this build 0.6.9 is not compiled, I try through this query:
ndk-build NDK_PROJECT_PATH=C:\Users\User\Desktop\libsamp APP_BUILD_SCRIPT=C:\Users\User\Desktop\libsamp\Android.mk NDK_APPLICATION_MK=C:\Users\User\Desktop\libsamp\Application.mk APP_STL=c++_static
Gives an error message: 
![C_F6jV9IrSU (1)](https://user-images.githubusercontent.com/46651099/56463579-dee64300-63df-11e9-9f5d-b288ba096faf.jpg)

**Comment by soly-olf** [comment]
maybe u show full screen?

**Comment by SteelSa** [comment]
![image](https://user-images.githubusercontent.com/46651099/56492614-0418a580-64f5-11e9-9f72-66ddfcf4293c.png)

**Comment by SteelSa** [comment]
Error file
[error.txt](https://github.com/4x11/build69/files/3102844/error.txt)
