### ISSUE TITLE
GTA SA Lite version.

### ISSUE THREAD

**Issue by qqwrv-f10eq** [4x11/build69#20]
This apk can be use for lite version ?

**Comment by soly-olf** [comment]
that not apk

**Comment by qqwrv-f10eq** [comment]
edit libsamp.so ?

**Comment by soly-olf** [comment]
lib != apk

**Comment by qqwrv-f10eq** [comment]
I know that. My question, If I want lite version to connect our sever, I need to edit apk or lib or something ?
