### ISSUE TITLE
Generate libsamp.so

### ISSUE THREAD

**Issue by kondzilla157** [4x11/build69#3]
I am trying to compile and generate "libsamp.so" for my server but I still do not know how to do it.. could you help me in the part of the command used to compile? The rest I know how to do

(I already own the Android NDK 19)

**Comment by KamikZMenu** [comment]
**Result:**
![problem_samp](https://user-images.githubusercontent.com/10608391/56473379-fe618800-6440-11e9-9001-ecc35a86553d.PNG)

**Comment by soly-olf** [comment]
#1

**Comment by kondzilla157** [comment]
Thx <3

**Comment by aktah** [comment]
Once you have libsamp.so and what to do next

**Comment by kondzilla157** [comment]
> Once you have libsamp.so and what to do next

The developers do not create any tutorial .. with more servers gets more popular .. since that is not what they want, congratulations

**Comment by qqwrv-f10eq** [comment]
I just want add our language (TH) to this client, Try hard for this.

**Comment by Wesley-cyber** [comment]
É possível compilar pelo celular?

**Comment by dalhy** [comment]
> **Result:**
> ![problem_samp](https://user-images.githubusercontent.com/10608391/56473379-fe618800-6440-11e9-9001-ecc35a86553d.PNG)

Olá kondzilla, me ajuda criar um APK.
