### ISSUE TITLE
Inject libsamp.so

### ISSUE THREAD

**Issue by kondzilla157** [4x11/build69#4]
I was able to generate the libsamp.so file and thought it would just unpack the .apk and put it in and then use the ZipSigner to sign the .apk.. I did it this way but it did not work out because whenever I click on Multiplayer the game closes

What is the right way to inject?

**Comment by soly-olf** [comment]
if u see "Multiplayer" button - u success inject lib

**Comment by kondzilla157** [comment]
Hm but.. why crash?

**Comment by kondzilla157** [comment]
> if u see "Multiplayer" button - u success inject lib

I used the Axwell test server client folder. Is that the problem? and I just set the host = ... and port = ...

**Comment by kondzilla157** [comment]
[samp_log.txt](https://github.com/4x11/build69/files/3105068/samp_log.txt)

log.. help me fix the crash Soly

**Comment by soly-olf** [comment]
that problem on code

**Comment by kondzilla157** [comment]
> that problem on code

Can you identify where?

I just downloaded the github files here and compiled it with build-ndk, the process worked out and I did not make any changes to the code before compiling

**Comment by kondzilla157** [comment]
Please soly :/

**Comment by kondzilla157** [comment]
I have the SaPatcher and I know to use the command to change the ip and port of libsamp.so but when I start the multiplayer continues the previous server ..

**Comment by SteelSa** [comment]
> У меня есть SaPatcher, и я знаю, чтобы использовать команду для изменения IP-адреса и порта libsamp.so, но при запуске мультиплеера продолжает предыдущий сервер ..
можно с вами связатся где-то кроме github?

**Comment by kondzilla157** [comment]
https://vk.com/onlyamember

> > У меня есть SaPatcher, и я знаю, чтобы использовать команду для изменения IP-адреса и порта libsamp.so, но при запуске мультиплеера продолжает предыдущий сервер ..
> > можно с вами связатся где-то кроме github?

**Comment by qqwrv-f10eq** [comment]
I'm too, server crash or maybe join previous server.

**Comment by SteelSa** [comment]
Please tell me what to do with SaPatcher

**Comment by qqwrv-f10eq** [comment]
I think change server ip:port from libsamp.so then inject apk later..

**Comment by qqwrv-f10eq** [comment]
> static_assert(sizeof(cryptor::string_encryptor) == 37);

static assertion failed

**Comment by SteelSa** [comment]
but how to embed it correctly in libsamp

**Comment by SteelSa** [comment]
Tell me, please

**Comment by zCrystal94** [comment]
> 
> 
> [samp_log.txt](https://github.com/4x11/build69/files/3105068/samp_log.txt)
> 
> log.. help me fix the crash Soly

I have same problem after compiled and injected it doesn't work crashes with same error on samp_log.txt

**Comment by aktah** [comment]
game crash after InitENG() I'm writing log after that !

**Comment by qqwrv-f10eq** [comment]
> 
> 	Log("Add Q");
> 	key.pos = curPos;
> 	Log("Add Q 1");
> 	key.symPos = ImVec2(curPos.x + defWidth * 0.4, curPos.y + m_fKeySizeY * 0.2);
> 	Log("Add Q 2");
> 	key.width = defWidth;
> 	Log("Add Q 3");
> 	key.code[LOWER_CASE] = 'q';
> 	Log("Add Q 4");
> 	key.code[UPPER_CASE] = 'Q';
> 	Log("Add Q 5");
> 	cp1251_to_utf8(key.name[LOWER_CASE], "q");
> 	Log("Add Q 6");
> 	cp1251_to_utf8(key.name[UPPER_CASE], "Q");
> 	Log("Add Q 7");
> 	key.id++;
> 	Log("Add Q 8");
> 	row->push_back(key);
> 	Log("Add Q 9");
> 	curPos.x += key.width;
> 

samp_log.txt stop at Add Q 8 on last line.

**Comment by qqwrv-f10eq** [comment]
[Image](https://uppic.cc/d/KFD2)

I got Connecting to: 0, Haha !!

**Comment by zCrystal94** [comment]
I see it crashes on keyboard.cpp on row->push_back(key); but debugging it.
I got connected but Server closed connection.

**Comment by qqwrv-f10eq** [comment]
How do you ?, 4x11 left us in the black hole.

**Comment by zCrystal94** [comment]
You should edit main.cpp
pNetGame = new CNetGame( 
			"IP",
			7777, 
			"nick",
			"");

**Comment by qqwrv-f10eq** [comment]
Yay, It work fine, The next issue is about our language for display.

**Comment by zCrystal94** [comment]
How did you fixed keyboard issues? on keyboard.cpp

**Comment by qqwrv-f10eq** [comment]
I just comment wait for 4x11 fix this issue !

**Comment by qqwrv-f10eq** [comment]
@4x11 help me !! iso_8859_11 to utf-8

https://en.wikipedia.org/wiki/Windows-1251 to
https://en.wikipedia.org/wiki/ISO/IEC_8859-11

**Comment by zCrystal94** [comment]
@aktah did you fixed row->push_back(key); issues?

**Comment by qqwrv-f10eq** [comment]
https://uppic.cc/d/KFEj 

I can't change language. sad !

**Comment by soly-olf** [comment]
> https://uppic.cc/d/KFEj
> 
> I can't change language. sad !

what lang?

**Comment by qqwrv-f10eq** [comment]
Thai, It should be "ฟหก", Also on SA-MP Server.

If setting like this: https://uppic.cc/d/KFEF, all be work fine

This issues come from Android ?

Here: https://uppic.cc/d/KFEp
1. SA-MP PC with window setting (I need display this on android)
2. SA-MP Android
3. SA-MP PC without setting

**Comment by zCrystal94** [comment]
I can't initialize keyboard it crashes  as i write before... can someone help me?

**Comment by aktah** [comment]
https://uppic.cc/d/KFEW
Bug, double press. I haven't fixed anything except adding a log debug.

**Comment by SteelSa** [comment]
> I can't initialize keyboard it crashes as i write before... can someone help me?

can i contact you except github?

**Comment by qqwrv-f10eq** [comment]
Nice work on english: https://uppic.cc/d/KFTn

**Comment by SteelSa** [comment]
aktah 
> Nice work on english: https://uppic.cc/d/KFTn

Please describe all your actions that you did to create an apk file and change the ip

**Comment by zCrystal94** [comment]
> 
> 
> > I can't initialize keyboard it crashes as i write before... can someone help me?
> 
> can i contact you except github?

Where?

**Comment by zCrystal94** [comment]
> 
> 
> Nice work on english: https://uppic.cc/d/KFTn

How did you fixed keyboard?

**Comment by SteelSa** [comment]
> > > Я не могу инициализировать клавиатуру, она вылетает, когда я пишу раньше ... кто-нибудь может мне помочь?
> > 
> > 
> > Могу ли я связаться с вами, кроме GitHub?
> 
> Куда?

Do you have any social networks?

**Comment by zCrystal94** [comment]
I have facebook, skype, whatsapp, instagram, tumblr

**Comment by SteelSa** [comment]
> У меня есть Facebook, Skype, WhatsApp, Instagram, Tumblr

You figured out how to fix the keyboard?

**Comment by zCrystal94** [comment]
> 
> 
> > У меня есть Facebook, Skype, WhatsApp, Instagram, Tumblr
> 
> You figured out how to fix the keyboard?

No, i tried, can you help me? It compile but when i put libsamp.so to apk client and i try to open multiplayer it crashes.

**Comment by SteelSa** [comment]
> > > У меня есть Facebook, Skype, WhatsApp, Instagram, Tumblr
> > 
> > 
> > You figured out how to fix the keyboard?
> 
> No, i tried, can you help me? It compile but when i put libsamp.so to apk client and i try to open multiplayer it crashes.

I am also looking for a solution to this problem, but not who does not want to help

**Comment by zCrystal94** [comment]
The only solution for bypass this problem is adding 
//pKeyBoard = new CKeyBoard(); 
but keyboard doesn't work anymore...

**Comment by SteelSa** [comment]
> The only solution for bypass this problem is adding
> //pKeyBoard = new CKeyBoard();
> but keyboard doesn't work anymore...


But where did you enter it?

**Comment by zCrystal94** [comment]
on main.cpp line 82

**Comment by SteelSa** [comment]
> on main.cpp line 82

 you figured out with SaPatcher?

**Comment by zCrystal94** [comment]
> 
> 
> > on main.cpp line 82
> 
> you figured out with SaPatcher?

Sapatcher doesn't work for me. But you can set your ip and your nick on main.cpp editing this

> 
> 
> You should edit main.cpp
> pNetGame = new CNetGame(
> "IP",
> 7777,
> "nick",
> "");

**Comment by SteelSa** [comment]
this line?
		pNetGame = new CNetGame( 
			encryptedAddress.decrypt(),
			port, 
			pSettings->Get().szNickName,
			pSettings->Get().szPassword);

**Comment by zCrystal94** [comment]
> 
> 
> this line?
> pNetGame = new CNetGame(
> encryptedAddress.decrypt(),
> port,
> pSettings->Get().szNickName,
> pSettings->Get().szPassword);

yes

**Comment by soly-olf** [comment]
> > > on main.cpp line 82
> > 
> > 
> > you figured out with SaPatcher?
> 
> Sapatcher doesn't work for me. But you can set your ip and your nick on main.cpp editing this
> 
> > You should edit main.cpp
> > pNetGame = new CNetGame(
> > "IP",
> > 7777,
> > "nick",
> > "");

what? saPatcher working

**Comment by SteelSa** [comment]
> > > > on main.cpp line 82
> > > 
> > > 
> > > you figured out with SaPatcher?
> > 
> > 
> > Sapatcher doesn't work for me. But you can set your ip and your nick on main.cpp editing this
> > > You should edit main.cpp
> > > pNetGame = new CNetGame(
> > > "IP",
> > > 7777,
> > > "nick",
> > > "");
> 
> what? saPatcher working


and how to install it or fill it in gta sa, please explain

**Comment by zCrystal94** [comment]
> 
> 
> > > > on main.cpp line 82
> > > 
> > > 
> > > you figured out with SaPatcher?
> > 
> > 
> > Sapatcher doesn't work for me. But you can set your ip and your nick on main.cpp editing this
> > > You should edit main.cpp
> > > pNetGame = new CNetGame(
> > > "IP",
> > > 7777,
> > > "nick",
> > > "");
> 
> what? saPatcher working

Not for me. But how can i fix  this keyboard problem? Do you know? how?

**Comment by soly-olf** [comment]
> > > > > on main.cpp line 82
> > > > 
> > > > 
> > > > you figured out with SaPatcher?
> > > 
> > > 
> > > Sapatcher doesn't work for me. But you can set your ip and your nick on main.cpp editing this
> > > > You should edit main.cpp
> > > > pNetGame = new CNetGame(
> > > > "IP",
> > > > 7777,
> > > > "nick",
> > > > "");
> > 
> > 
> > what? saPatcher working
> 
> Not for me. But how can i fix this keyboard problem? Do you know? how?

yes, i know

**Comment by SteelSa** [comment]
> > > > > > on main.cpp line 82
> > > > > 
> > > > > 
> > > > > you figured out with SaPatcher?
> > > > 
> > > > 
> > > > Sapatcher doesn't work for me. But you can set your ip and your nick on main.cpp editing this
> > > > > You should edit main.cpp
> > > > > pNetGame = new CNetGame(
> > > > > "IP",
> > > > > 7777,
> > > > > "nick",
> > > > > "");
> > > 
> > > 
> > > what? saPatcher working
> > 
> > 
> > Not for me. But how can i fix this keyboard problem? Do you know? how?
> 
> yes, i know

Do not tell me how to solve it?

**Comment by zCrystal94** [comment]
> 
> 
> > > > > on main.cpp line 82
> > > > 
> > > > 
> > > > you figured out with SaPatcher?
> > > 
> > > 
> > > Sapatcher doesn't work for me. But you can set your ip and your nick on main.cpp editing this
> > > > You should edit main.cpp
> > > > pNetGame = new CNetGame(
> > > > "IP",
> > > > 7777,
> > > > "nick",
> > > > "");
> > 
> > 
> > what? saPatcher working
> 
> and how to install it or fill it in gta sa, please explain

I downloaded a apk for gta samp client like some rp server edited it by apk editor pro for android and i replaced libsamp.so, after i resigned it again and it worked

**Comment by zCrystal94** [comment]
> 
> 
> > > > > > on main.cpp line 82
> > > > > 
> > > > > 
> > > > > you figured out with SaPatcher?
> > > > 
> > > > 
> > > > Sapatcher doesn't work for me. But you can set your ip and your nick on main.cpp editing this
> > > > > You should edit main.cpp
> > > > > pNetGame = new CNetGame(
> > > > > "IP",
> > > > > 7777,
> > > > > "nick",
> > > > > "");
> > > 
> > > 
> > > what? saPatcher working
> > 
> > 
> > Not for me. But how can i fix this keyboard problem? Do you know? how?
> 
> yes, i know

how? can you explain please?
it crashes here: on keyboard.cpp
row->push_back(key);

**Comment by SteelSa** [comment]
> > > > > > > on main.cpp line 82
> > > > > > 
> > > > > > 
> > > > > > you figured out with SaPatcher?
> > > > > 
> > > > > 
> > > > > Sapatcher doesn't work for me. But you can set your ip and your nick on main.cpp editing this
> > > > > > You should edit main.cpp
> > > > > > pNetGame = new CNetGame(
> > > > > > "IP",
> > > > > > 7777,
> > > > > > "nick",
> > > > > > "");
> > > > 
> > > > 
> > > > what? saPatcher working
> > > 
> > > 
> > > Not for me. But how can i fix this keyboard problem? Do you know? how?
> > 
> > 
> > yes, i know
> 
> how? can you explain please?
> it crashes here: on keyboard.cpp
> row->push_back(key);

so always, knowledgeable people just ignore everything

**Comment by qqwrv-f10eq** [comment]
I can fix that, but I don't know why. I just defined them

**Comment by zCrystal94** [comment]
> 
> 
> I can fix that, but I don't know why. I just defined them

Can you explain what do you did? please.
Or can you upload it?

**Comment by qqwrv-f10eq** [comment]
buid & fix, I try on this project 2-3 day ago, without doc.

**Comment by zCrystal94** [comment]
> 
> 
> buid & fix, I try on this project 2-3 day ago, without doc.

What do you fixed?

**Comment by SteelSa** [comment]
> > buid & fix, I try on this project 2-3 day ago, without doc.
> 
> What do you fixed?

Please describe all your actions that you did to create an apk file and change the ip

**Comment by SteelSa** [comment]
> buid & fix, I try on this project 2-3 day ago, without doc.


 Please describe all your actions that you did to create an apk file up to ip

**Comment by qqwrv-f10eq** [comment]
game crash when weapon spawn ? @soly-olf

**Comment by SteelSa** [comment]
> game crash when weapon spawn ? @soly-olf


Please tell me how you fixed the crashes when you press the multiplayer.

**Comment by qqwrv-f10eq** [comment]
I tell u, I don't know just Log() everywhere.

**Comment by SteelSa** [comment]
> I tell u, I don't know just Log() everywhere.

You can upload your files to GitHub that you used to compile libsamp.so

**Comment by zCrystal94** [comment]
What do you used? But i don't understand why you don't help Us by fixing the code...

**Comment by aktah** [comment]
I do nothing much.
Here: https://pastebin.com/ZZJ2FAb8

**Comment by soly-olf** [comment]
> game crash when weapon spawn ? @soly-olf

 no

**Comment by aktah** [comment]
What I can do, Thai language always show "??????" Or I can mod fonts ?

ISO-8859-11: https://pastebin.com/raw/hsdZAFGK

**Comment by aktah** [comment]
> > game crash when weapon spawn ? @soly-olf
> 
> no

Android can't take damage from PC Client.

**Comment by Tobi038** [comment]
> https://vk.com/onlyamember
> 
> > > У меня есть SaPatcher, и я знаю, чтобы использовать команду для изменения IP-адреса и порта libsamp.so, но при запуске мультиплеера продолжает предыдущий сервер ..
> > > можно с вами связатся где-то кроме github?

Kondizila, me chama no WhatsApp (21) 9 9277-4023

**Comment by Dukinja** [comment]
Please explain me how to change ip and port
