### ISSUE TITLE
What are you using for build this ?

### ISSUE THREAD

**Issue by aktah** [4x11/build69#5]
Android NDK: android-14 is unsupported. Using minimum supported version android-16.
make: Entering directory `D:/repositity/build69/jni'
C:/Users/srysgag/AppData/Local/Android/Sdk/ndk-bundle/build//../build/core/add-application.mk:178: *** Android NDK: APP_STL gnustl_static is no longer supported. Please switch to either c+
+_static or c++_shared. See https://developer.android.com/ndk/guides/cpp-support.html for more information.    .  Stop

I tried 6-7 hours, Please help!

**Comment by DeTroitSP** [comment]
You need to introduce a few changes in the Application.mk:

APP_ABI := armeabi-v7a
APP_PLATFORM := android-16
APP_MODULES := samp
APP_STL := c++_static

**Comment by aktah** [comment]
I got libsamp.so and then use saPatcher and what next ?
