### ISSUE TITLE
saPather: static assert failed

### ISSUE THREAD

**Issue by qqwrv-f10eq** [4x11/build69#7]
> static_assert(sizeof(cryptor::string_encryptor) == 37);

on MSV 2019.

**Comment by soly-olf** [comment]
use vs2017

**Comment by qqwrv-f10eq** [comment]
Now Thai Language, Have a nice work.
https://uppic.cc/d/KFC7

If need to dev more thing packet from SA-MP, I need to rush on Raknet/RPC ?
I'm not a good programmer but I’m a fast learner. haha

**Comment by qqwrv-f10eq** [comment]
Still not work on vs2017
