### ISSUE TITLE
random crash when found player.

### ISSUE THREAD

**Issue by qqwrv-f10eq** [4x11/build69#8]
Log: "RPC: WorldPlayerAdd"

pRemotePlayer->Spawn(byteTeam, iSkin, &vecPos, fRotation, dwColor, byteFightingStyle, bVisible);

**Comment by soly-olf** [comment]
u disable shadow & car reflection?

**Comment by qqwrv-f10eq** [comment]
Already, crash on spectate state and that guys AFK

Maybe I think when client have a lot of load. (etc Map, Player)
